@startuml
title Диаграмма деятельности менеджера системы ТОИР

start

:Открыть систему ТОИР;
:Ввести email и пароль;

if (Учетные данные верны?) then (да)
  :Открыть дашборд менеджера;
else (нет)
  :Показать ошибку авторизации;
  stop
endif

repeat
  :Выбрать раздел системы;

  if (Раздел "ТО"?) then (да)
    :Открыть планирование ТО;
    :Просмотреть таблицу или календарь ТО;

    if (Нужно создать план ТО?) then (да)
      :Выбрать оборудование;
      :Выбрать вид ТО;
      :Указать плановую дату;
      :Указать трудоемкость и примечания;
      :Создать план ТО;
    elseif (Нужно назначить ответственного?) then (да)
      :Открыть план ТО;
      :Выбрать ответственного исполнителя;
      :Сохранить изменения;
    elseif (Нужно изменить план ТО?) then (да)
      :Открыть план ТО;
      :Изменить дату, статус, ответственного или примечания;
      :Сохранить изменения;
    elseif (Нужно отменить план ТО?) then (да)
      :Открыть план ТО;
      :Установить статус "Отменено";
      :Сохранить изменения;
    else (нет)
      :Контролировать запланированные и просроченные работы;
    endif

  elseif (Раздел "Аналитика"?) then (да)
    :Просмотреть план-факт ТО;
    :Оценить выполнение работ в срок;
    :Просмотреть статистику по оборудованию;
    :Выявить оборудование с повышенным числом ремонтов;

  else (другое)
    :Вернуться на дашборд;
  endif

repeat while (Менеджер продолжает работу?) is (да)

:Выйти из системы;
stop

@enduml
